# space shell init -- generated by `space init zsh`
# Add to your ~/.zshrc:
#   eval "$(space init zsh)"

# Wrapper: intercepts TUI/cd commands, passes read-only commands through directly.
# Required for `space go` (directory change) and TUI commands to work correctly.
space() {
  case "${1:-}" in
    ls|list|status|st|repos|completions|init|__complete|mcp|--version|--help|-h|-V)
      command space "$@"
      ;;
    *)
      local cdfile="${TMPDIR:-/tmp}/.space_cd_$$"
      __SPACE_CD_FILE__="$cdfile" command space "$@"
      local ret=$?
      if [[ -s "$cdfile" ]]; then
        cd -- "$(<"$cdfile")"
      fi
      rm -f "$cdfile" 2>/dev/null
      return $ret
      ;;
  esac
}
